version: '3.9' 

services:  
  web:
    container_name: aiohttp-web
    build: .
    restart: unless-stopped
    ports:
      - 8200:8200
    depends_on:
      - db

  db:
    container_name: aiohttp-db
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-db}

volumes:
  postgres_data:
